# to replicate -> conda env create --file environment.yml
name: proyecto_nba_mvp
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel==6.29.3
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - seaborn=0.13.1
  - numpy=1.25.2
  - python=3.10.12